# OpenTelemetry Collector Configuration
# 
# NOTE: S3 bulk storage and refinery pipelines are commented out below.
# Uncomment them when ready to use those destinations.
# Currently only direct Honeycomb export is enabled.



extensions:
  pprof:
    endpoint: 0.0.0.0:1777
  
  # Debug logging extension
  zpages:
    endpoint: 0.0.0.0:55679
  
  # Health check extension
  health_check:
    endpoint: 0.0.0.0:8889

receivers:
  # Fluent Bit receiver for log forwarding
  fluentforward:
    endpoint: 0.0.0.0:8006

  # Prometheus receiver for scraping collector metrics
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 30s
          static_configs:
            - targets: ['localhost:8888']

  otlp/main:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        include_metadata: true
        keepalive:
          server_parameters:
            max_connection_age: 1m0s
            max_connection_age_grace: 5m0s
            max_connection_idle: 1m0s
            time: 2h
            timeout: 20s
        max_recv_msg_size_mib: 4
      http:
        endpoint: 0.0.0.0:4318
        include_metadata: true

processors:
  batch/main:
    send_batch_max_size: 0
    send_batch_size: 1
    timeout: 1s

  # Note: removeemptyvalues processor removed - not available in this collector version

  # Filter processor to send only error severity logs to Honeycomb
  filter/errors_only:
    logs:
      log_record:
        - 'severity_text == "ERROR"'

  transform/parse_timestamp:
    error_mode: ignore
    log_statements:
      - context: log
        statements:
          - set(time, Time(body["ts"], "%Y-%m-%dT%H:%M:%S.%f%z", "")) where true

  transform/cleanup_logs:
    error_mode: ignore
    log_statements:
      - context: log
        statements:
          - delete_key(body, "ts") where true

exporters:
  # Debug exporter to see what data is flowing
  debug:
    verbosity: detailed

  # S3 bulk storage exporter
  awss3/bulk_storage:
    s3uploader:
      compression: gzip
      file_prefix: ""
      region: ${AWS_DEFAULT_REGION}
      s3_bucket: ${S3_BUCKET_NAME}
      s3_partition_format: year=%Y/month=%m/day=%d/hour=%H/minute=%M
      s3_prefix: "otel"
    marshaler: 'otlp_proto'
    sending_queue:
      batch:
        flush_timeout: 30s
        max_size: 50000
        min_size: 50000
      enabled: true
      queue_size: 500000
      sizer: items
    timeout: 30s


  # Refinery exporters (commented out - uncomment when ready)
  # otlp/honeycomb_logs:
  #   compression: gzip
  #   endpoint: refinery.honeycomb.io:443
  #   headers:
  #     x-honeycomb-team: ${HONEYCOMB_API_KEY}
  #   retry_on_failure:
  #     enabled: true
  #     initial_interval: 5s
  #     max_elapsed_time: 300s
  #     max_interval: 30s
  #   sending_queue:
  #     enabled: false
  #   tls:
  #     ca_file: ""
  #     insecure: false
  #     insecure_skip_verify: false

  # otlp/honeycomb_traces:
  #   compression: gzip
  #   endpoint: refinery.honeycomb.io:443
  #   headers:
  #     x-honeycomb-team: ${HONEYCOMB_API_KEY}
  #   retry_on_failure:
  #     enabled: true
  #     initial_interval: 5s
  #     max_elapsed_time: 300s
  #     max_interval: 30s
  #   sending_queue:
  #     enabled: false
  #   tls:
  #     ca_file: ""
  #     insecure: false
  #     insecure_skip_verify: false

  # Direct Honeycomb exporters (active)
  otlp/honeycomb_direct_logs:
    compression: gzip
    endpoint: api.honeycomb.io:443
    headers:
      x-honeycomb-team: ${HONEYCOMB_API_KEY}
      x-honeycomb-dataset: "otel-logs"
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_elapsed_time: 300s
      max_interval: 30s
    sending_queue:
      enabled: true
    tls:
      insecure: false

  otlp/honeycomb_direct_metrics:
    compression: gzip
    endpoint: api.honeycomb.io:443
    headers:
      x-honeycomb-team: ${HONEYCOMB_API_KEY}
      x-honeycomb-dataset: "otel-metrics"
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_elapsed_time: 300s
      max_interval: 30s
    sending_queue:
      enabled: true
    tls:
      insecure: false

  # Collector operational metrics exporter
  otlp/honeycomb_collector_metrics:
    compression: gzip
    endpoint: api.honeycomb.io:443
    headers:
      x-honeycomb-team: ${HONEYCOMB_API_KEY}
      x-honeycomb-dataset: "collector-metrics"
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_elapsed_time: 300s
      max_interval: 30s
    sending_queue:
      enabled: true
    tls:
      insecure: false

  otlp/honeycomb_direct_traces:
    compression: gzip
    endpoint: api.honeycomb.io:443
    headers:
      x-honeycomb-team: ${HONEYCOMB_API_KEY}
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_elapsed_time: 300s
      max_interval: 30s
    sending_queue:
      enabled: true
    tls:
      insecure: false

service:
  extensions: [pprof, zpages, health_check]
  telemetry:
    logs:
      level: debug
      development: true
      encoding: console
    metrics:
      level: detailed
  pipelines:
    # S3 archival pipelines
    logs/bulk_storage:
      receivers:
        - otlp/main
        - fluentforward
      processors:
        - batch/main
      exporters:
        - debug
        - awss3/bulk_storage

    metrics/bulk_storage:
      receivers:
        - otlp/main
      processors:
        - batch/main
      exporters:
        - debug
        - awss3/bulk_storage

    traces/bulk_storage:
      receivers:
        - otlp/main
      processors:
        - batch/main
      exporters:
        - debug
        - awss3/bulk_storage

    # Honeycomb via Refinery pipelines (commented out - uncomment when ready)
    # logs/honeycomb:
    #   receivers:
    #     - otlp/main
    #     - fluentforward
    #   processors:
    #     - transform/parse_timestamp
    #     - transform/cleanup_logs
    #     - batch/main
    #   exporters:
    #     - otlp/honeycomb_logs

    # traces/honeycomb:
    #   receivers:
    #     - otlp/main
    #   processors:
    #     - batch/main
    #   exporters:
    #     - otlp/honeycomb_traces

    # Direct to Honeycomb pipelines (active)
    logs/honeycomb_direct:
      receivers:
        - otlp/main
        - fluentforward
      processors:
        - filter/errors_only
        - batch/main
      exporters:
        - debug
        - otlp/honeycomb_direct_logs

    # Application metrics pipeline
    metrics/honeycomb_direct:
      receivers:
        - otlp/main
      processors:
        - batch/main
      exporters:
        - debug
        - otlp/honeycomb_direct_metrics

    # Collector operational metrics pipeline
    metrics/collector_operations:
      receivers:
        - prometheus
      processors:
        - batch/main
      exporters:
        - debug
        - otlp/honeycomb_collector_metrics

    traces/honeycomb_direct:
      receivers:
        - otlp/main
      processors:
        - batch/main
      exporters:
        - debug
        - otlp/honeycomb_direct_traces
