services:
  collector:
    image: otel/opentelemetry-collector-contrib:${COLLECTOR_VERSION:-latest}
    container_name: otel-collector
    hostname: collector
    restart: unless-stopped
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8006:8006"
      - "8888:8888"
      - "8889:8889"
    volumes:
      - ./collector-config.yaml:/etc/otelcol-contrib/config.yaml:ro
    environment:
      - HONEYCOMB_API_KEY=${HONEYCOMB_API_KEY:?HONEYCOMB_API_KEY is required}
      # AWS Credentials (optional - use either access keys OR IAM role)
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME:?S3_BUCKET_NAME is required}
    deploy:
      resources:
        limits:
          memory: ${COLLECTOR_MEMORY:-512m}
          cpus: ${COLLECTOR_CPU:-0.3}
        reservations:
          memory: 128m
          cpus: 0.1
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8889/"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  sample-app:
    build: 
      context: ./sample-app
      dockerfile: Dockerfile
    container_name: sample-app
    hostname: sample-app
    restart: unless-stopped
    depends_on:
      - collector
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317
      - ENVIRONMENT=${ENVIRONMENT:-docker-demo}
      - OTEL_SERVICE_NAME=sample-telemetry-app
      - OTEL_SERVICE_VERSION=1.0.0
      - OTEL_SERVICE_INSTANCE_ID=docker-instance
      - OTEL_LOG_LEVEL=${OTEL_LOG_LEVEL:-warn}
    deploy:
      resources:
        limits:
          memory: 128m
          cpus: 0.1
        reservations:
          memory: 32m
          cpus: 0.05
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

networks:
  default:
    name: otel-demo
    driver: bridge